# Request
uint16 map_uuid # Required. UUID of the map corresponding to the route_graph/node
string route_graph_name # Required
geometry_msgs/Pose route_node_pose # Required
string route_node_name # Optional, default: none
---
# Response
bool success # Indicate successful run of service
uint16 node_uuid # 16-bit unique identification number
string message # Error messages
