## Request

# Recording Types (enum)
#
# BUFFER_FILE: Delete a recording from the buffer dir
# KEEP_SESSION: Delete a session from keep dir
uint8 BUFFER_FILE=0
uint8 KEEP_SESSION=1


# Type of request (see options above)
uint8 delete_request_type

# File/session name
string name

---
## Response

# Indicate successful run of service
bool success

# Error messages
string error
