# Request
uint16 map_uuid # Required
string route_graph_name # Required
uint16 node_uuid # Required
geometry_msgs/Pose new_pose # Required
string new_name # Optional
---
# Response
bool success # Indicate successful run of service
string message # Error messages
