## Request

# ID of the map that the route belongs to
uint16 map_id

# Name of the route graph that the edge belongs to
string route_graph_name

# Required. UUID of the route node
uint16 node_id

# Optional (Not implemented), name of the route node
string node_name
---
## Response

# Indicate successful run of service
bool success

# Route node details
polymath_msgs/RouteNode node

# Error messages
string message
