## Request

# Name of the bag / data source (Required)
string data_source

# Name of the map (Recommended: default name - timestamp)
string map_name
---
## Response

# Indicate successful run of service
bool success

# 16-bit unique identification number
uint16 map_id

# Error messages
string message
