## Request

---
## Response

# Indicate successful run of service
bool success

# Bag recordings from each category
BagRecording[] active_recordings
BagRecording[] buffer_recordings
BagRecording[] keep_sessions

# Error messages
string error
