## Request

# Start time for retention
builtin_interfaces/Time start_time

# End time for retention
builtin_interfaces/Time end_time

# Session suffix (optional, recommended)
string session_suffix

---
## Response

# Indicate successful run of service
bool success

# Error messages
string error
