## Request

---
## Response

# Indicate successful run of service
bool success

# If success is true, message will contain bag file name
# If success is false, message will contain error messages
string message
